rule all:
    input:
        "results/output_contigs.fasta"

rule run_assembly:
    input:
        "data/input_reads.fasta"
    output:
        "results/output_contigs.fasta"
    shell:
        "python3 ./assembly {input} {output}"
