rule all:
    input:
        "results/output.txt"

rule run_mapper:
    input:
        ref="data/reference.fasta",
        reads="data/reads.fasta"
    output:
        "results/output.txt"
    shell:
        "python3 mapper.py {input.ref} {input.reads} {output}"
